# .github/workflows/generate-default-page-template.yml

name: Generate Default Page Template of Contents

on:
  workflow_dispatch:

permissions:
  contents: write  # GITHUB_TOKEN에 쓰기 권한 부여

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 최신 버전 사용

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up API Key
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: echo "PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}" >> $GITHUB_ENV

      - name: Run content generation script
        run: python scripts/generate-default-page-template.py

      - name: Commit and push changes
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add .
          git commit -m 'Auto-generated content [skip ci]' || echo "No changes to commit"
          git push  # 단순화된 push 명령어 사용
